export const CART_ACTION_TYPES = {
  TOGGLE_CART: "cart/TOGGLE_CART",
  SET_CART_ITEMS: "cart/SET_CART_ITEMS",
  SET_CART_COUNT: "cart/SET_CART_COUNT",
  SET_CART_TOTAL: "cart/SET_CART_TOTAL",
  CLEAR_ALL_CART_ITEMS: "cart/CLEAR_ALL_CART_ITEMS",
};
